RENDER_TOP_VIEW = "top_view"
RENDER_ROOF = "roof"
RENDER_STRUCTURE_FACADES = "structure_facades"
RENDER_PATH = "path"
RENDER_SITE_FACADES = "site_facades"
RENDER_MATERIALS = "materials"
RENDER_WORLDGEN = "worldgen"
RENDER_ALL = "all"

BLOCK_PX = 30

TEXTURE_TOP = "top"
TEXTURE_SIDE = "side"

RENDER_PADDING = 50
PATH_VIEW_TOP_MARGIN = 80
LAYER_PANEL_TOP_MARGIN = 120
SITE_FACADES_TOP_MARGIN = 80

EMPTY_CELL_COLOR = (245, 245, 245)
EMPTY_CELL_OUTLINE = (230, 230, 230)
DEFAULT_SITE_STRUCTURE_LAYERS = [0, 1]
DEFAULT_WORLDGEN_BASE_Y = -60
