structure: well
stages:
- stage: 1
  path: stage1/stage.yaml
  output_folder: stage1_well
dimension: overworld
grid:
  site_structure_layers:
  - 0
  worldgen_base_y: -60
  site_width: 11
  site_depth: 11
  placement: center
  offset_x: 2
  offset_z: 2
  path_orientation: horizontal
  path_width: 3
  trim_block: GRAVEL
  path_variety_blocks:
  - GRAVEL
  - DIRT
  - COBBLESTONE
  - COBBLESTONE#mossy
site_ground:
- - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
- - GRASS
  - GRASS
  - GRASS
  - GRAVEL
  - DIRT
  - GRAVEL
  - DIRT_PATH
  - GRAVEL
  - GRASS
  - GRASS
  - GRASS
- - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
- - GRASS
  - GRAVEL
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRAVEL
  - GRASS
- - GRASS
  - GRAVEL
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - DIRT_PATH
  - GRASS
- - GRASS
  - DIRT_PATH
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - DIRT_PATH
  - GRASS
- - GRASS
  - DIRT_PATH
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - DIRT_PATH
  - GRASS
- - GRASS
  - GRAVEL
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRAVEL
  - GRASS
- - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
- - GRASS
  - GRASS
  - GRASS
  - GRAVEL
  - DIRT_PATH
  - DIRT
  - DIRT_PATH
  - GRAVEL
  - GRASS
  - GRASS
  - GRASS
- - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
  - GRASS
