structure: well
stages:
- stage: 1
  path: stage1/stage.yaml
  output_folder: stage1_well
- stage: 2
  path: stage2/stage.yaml
  output_folder: stage2_well
dimension: overworld
grid:
  site_structure_layers:
  - 0
  worldgen_base_y: -60
  site_width: 11
  site_depth: 11
  placement: center
  offset_x: 2
  offset_z: 2
  groups:
  - Main
site_ground:
- - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:gravel
  - minecraft:dirt
  - minecraft:gravel
  - minecraft:dirt_path
  - minecraft:gravel
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:gravel
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:gravel
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:gravel
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:dirt_path
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:dirt_path
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:dirt_path
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:dirt_path
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:dirt_path
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:gravel
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:gravel
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:gravel
  - minecraft:dirt_path
  - minecraft:dirt
  - minecraft:dirt_path
  - minecraft:gravel
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
- - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
  - minecraft:grass_block
