STRUCTURE_DATA = {
    0: [
        "M C M C M M C C M M C C M C M",
        "C P P P P P P P M P P P P P C",
        "M P P P P P P P P P P P P P M",
        "C P P P P P P P M P P P P P C",
        "C P P P P P P P M C C M C M C",
        "C P P P P P P P C P P P P P M",
        "C P P P P P P P P P P P P P M",
        "M P P P P P P P M P P P P P C",
        "C M C M C C M M C C M M C M C",
        ". . . sn sn sn . . . . . . . . . ."],
    1: [
        "L P P P P P P P L P P P P P L",
        "P . . . . . . . P . . . bef beh P",
        "P . . . . . . . dbe . . . . . P",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . L P P P P P L",
        "P . . . . . . . P . . . . T P",
        "P . . . . . . . . . . . . F P",
        "P . . . . . . . P xnl xnr . . . P",
        "L P P P dbn P P P L P P P P P L",
        ". . . . . . . . . . . . . . .  ."],
    2: [
        "L P P P P P P P L P P owe P P L",
        "P . . . . . . . P . . . . . P",
        "ons . . . . . . . dte . . . . . osn",
        "P . . . . . . . P . . in . . P",
        "P ie . . . . . iw L P P P P P L",
        "P . . . . . . . P . . is . . P",
        "ons . . . . . . . . . . . . . osn",
        "P . . . . . . . P . . . . . P",
        "L P oew P dtn P oew  P L P P oew P P L",
        ". . . . . . . . . . . . . . .  ."],
    3: [
        "L P P P P P P P L P P P P P L",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . L P P P P P L",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "L P P P P P P P L P P P P P L",
        ". . . . . . . . . . . . . . .  ."],
    4: [
        "L LS LS P P P P P L P P P P P L",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . L P P P P P L",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "P . . . . . . . P . . . . . P",
        "L P P P P P P P L P P P P P L",
        ". . . . . . . . . . . . . . .  ."],
    5: [
        "ss_ol ss ss ss ss ss ss ss ss_or . . . . . . .",
        "se P P P P P P P sw . . . . . . .",
        "se . . . . . . . sw . . . . . . .",
        "se . . . . . . . sw . . . . . . .",
        "se . . . . . . . sw . . . . . . .",
        "se . . . . . . . sw . . . . . . .",
        "se . . . . . . . sw . . . . . . .",
        "se . . . . . . . sw . . . . . . .",
        "sn_or sn sn sn sn sn sn sn sn_ol . . . . . . .",
        ". . . . . . . . . . . . . . . ."],
    6: [
        ". . . . . . . . . . . . . . . . .",
        ". l l l l l l l . . . . . . .",
        ". l l l l l l l . . . . . . .",
        ". l l l l l l l . . . . . . .",
        ". l l l l l l l . . . . . . .",
        ". l l l l l l l . . . . . . .",
        ". l l l l l l l . . . . . . .",
        ". l l l l l l l . . . . . . .",
        ". . . . . . . . . . . . . . . . .",
        ". . . . . . . . . . . . . . . . ."]
}

STRUCTURE_CONFIG = {    
    "structure": "residence",
    "stage": 2,
    "name": "Residence Stage 2",
    "output_folder": "stage2_residence",
    "data": STRUCTURE_DATA,
    "size": 30,
    "struct_w": 15,
    "struct_h": 10,
    "offset_x": 10,
    "offset_z": 4,
    "floor_map": {
        "Floor 1": [0, 1, 2, 3, 4],
        "Roof": [5, 6]
    }
}