"""Tests for scripts/build_forward_feedback_index.py."""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts.build_forward_feedback_index import (
    REPO_ROOT,
    apply_duplicate_of,
    build_index,
    index_is_current,
    make_ff_uid,
    question_fingerprint,
    render_index_yaml,
    write_index,
)
from scripts.lessons_coverage_lib import (
    ForwardFeedbackItem,
    derive_feedback_card_category,
    parse_feedback_card_items,
    parse_forward_feedback_items,
)

GC5_ITEM = """
- **Question:** Should registry yaml paths stay schema-internal?
  **Risk Level:** 4 | **Priority:** High | **Importance:** Primary
  **Impact Scope:** system-wide
  **References:** sig:forward-feedback-index
  **Mitigation:** Extend _SCHEMA_INTERNAL_PATHS in same PR.
  **Detail:** Parity checks fail when index paths land in AGENTS table.
"""


def _gc5_body(*, codebase_scope: str = "local", codebase_risk: int = 2) -> str:
    governance = GC5_ITEM
    low = """
- **Question:** Low-priority skill question?
  **Risk Level:** 2 | **Priority:** Low
  **Impact Scope:** local
  **References:** sig:test
"""
    codebase = f"""
- **Question:** Codebase ranking question?
  **Risk Level:** {codebase_risk} | **Priority:** Medium | **Importance:** Secondary
  **Impact Scope:** {codebase_scope}
  **References:** sig:codebase-q
"""
    categories = (
        ("Governance", governance),
        ("Skill", low),
        ("Rule", low),
        ("Codebase", codebase),
        ("Prompt pattern", low),
        ("Routing", low),
    )
    sections = [f"### {name}\n{body.strip()}" for name, body in categories]
    return "## Forward-looking feedback (2026-06-27)\n\n" + "\n\n".join(sections) + "\n"


def _write_closed_card(
    done_dir: Path,
    name: str,
    *,
    body: str,
    labels: str = '["agent"]',
    completed_at: str = "2026-06-27T20:00:00.000Z",
) -> Path:
    path = done_dir / name
    path.write_text(
        "---\n"
        f"labels: {labels}\n"
        f'completedAt: "{completed_at}"\n'
        "epic: ForwardFeedbackRegistry\n"
        "---\n\n"
        "## Lessons captured (2026-06-27)\n\n"
        "- lesson bullet\n\n"
        f"{body}",
        encoding="utf-8",
    )
    return path


@pytest.fixture
def ff_features(tmp_path: Path):
    done = tmp_path / ".devtool" / "features" / "done"
    done.mkdir(parents=True)
    return tmp_path, done


def test_parse_forward_feedback_items_extracts_fields():
    text = _gc5_body()
    items = parse_forward_feedback_items(text)
    assert len(items) == 6
    governance = next(item for item in items if item.category == "Governance")
    assert governance.question.startswith("Should registry yaml")
    assert governance.risk_level == 4
    assert governance.impact_scope == "system-wide"
    assert governance.importance == "Primary"
    assert governance.mitigation is not None


def test_make_ff_uid_stable():
    item = ForwardFeedbackItem(
        category="Codebase",
        question="Same question?",
        seq=1,
    )
    uid_a = make_ff_uid(".devtool/features/done/foo.md", item)
    uid_b = make_ff_uid(".devtool/features/done/foo.md", item)
    assert uid_a == uid_b
    assert uid_a.startswith("ff-foo-codebase-01-")


def test_build_index_collects_closed_cards(ff_features):
    repo_root, done = ff_features
    _write_closed_card(done, "card-a.md", body=_gc5_body())
    _write_closed_card(
        done,
        "no-ff.md",
        body="",
    )
    payload, _warnings = build_index(repo_root=repo_root)
    assert len(payload["items"]) == 6
    ids = {row["id"] for row in payload["items"]}
    assert len(ids) == 6
    assert all(row["status"] in ("open", "duplicate") for row in payload["items"])
    assert payload["items"][0]["source_card"].endswith("card-a.md")


def test_build_index_skips_inquiry_labels(ff_features):
    repo_root, done = ff_features
    _write_closed_card(
        done,
        "inquiry.md",
        body=_gc5_body(),
        labels='["inquiry"]',
    )
    payload, _warnings = build_index(repo_root=repo_root)
    assert payload["items"] == []


def test_index_is_current_roundtrip(ff_features, tmp_path: Path):
    repo_root, done = ff_features
    _write_closed_card(done, "card-a.md", body=_gc5_body())
    payload, _warnings = build_index(repo_root=repo_root)
    out = tmp_path / "forward-feedback-index.yaml"
    write_index(payload, output_path=out)
    assert index_is_current(payload, output_path=out)
    payload["items"][0]["question"] = "mutated"
    assert not index_is_current(payload, output_path=out)


def test_render_index_yaml_has_generated_header(ff_features):
    repo_root, done = ff_features
    _write_closed_card(done, "card-a.md", body=_gc5_body())
    payload, _warnings = build_index(repo_root=repo_root)
    rendered = render_index_yaml(payload)
    assert rendered.startswith("# Generated by scripts/build_forward_feedback_index.py")


def _duplicate_question_body(question: str) -> str:
    item = f"""
- **Question:** {question}
  **Risk Level:** 3 | **Priority:** Medium
  **Impact Scope:** local
  **References:** sig:test
"""
    return "## Forward-looking feedback (2026-06-27)\n\n### Governance\n" + item.strip() + "\n"


def test_build_index_marks_duplicate_question_fingerprints(ff_features):
    repo_root, done = ff_features
    shared = "Should duplicate questions link with duplicate_of?"
    _write_closed_card(done, "card-a.md", body=_duplicate_question_body(shared))
    _write_closed_card(done, "card-b.md", body=_duplicate_question_body(shared))
    payload, warnings = build_index(repo_root=repo_root)
    assert len(payload["items"]) == 2
    canonical = next(row for row in payload["items"] if row["source_card"].endswith("card-a.md"))
    duplicate = next(row for row in payload["items"] if row["source_card"].endswith("card-b.md"))
    assert "duplicate_of" not in canonical
    assert duplicate["duplicate_of"] == canonical["id"]
    assert len(warnings) == 1
    assert "duplicate_of" in warnings[0]


def test_apply_duplicate_of_is_advisory_only():
    rows = [
        {"id": "ff-a", "question": "Same?"},
        {"id": "ff-b", "question": "Same?"},
    ]
    warnings = apply_duplicate_of(rows)
    assert rows[1]["duplicate_of"] == "ff-a"
    assert len(warnings) == 1


def test_question_fingerprint_normalizes_whitespace():
    assert question_fingerprint("  foo?  ") == question_fingerprint("foo?")


CARD_DONE_DOC_PATHS = (
    REPO_ROOT / "AGENTS.md",
    REPO_ROOT / ".cursor/rules/agent-routing.mdc",
    REPO_ROOT / ".cursor/skills/kanban-markdown/SKILL.md",
    REPO_ROOT / ".cursor/skills/kanban-markdown/reference.md",
)


def test_card_done_doc_parity_mentions_forward_feedback_index_rebuild():
    needle = "build_forward_feedback_index.py"
    for path in CARD_DONE_DOC_PATHS:
        text = path.read_text(encoding="utf-8")
        assert needle in text, f"{path} missing {needle}"
        assert "build_lessons_index.py" in text, f"{path} missing lessons index pairing"


FEEDBACK_CARD_BODY = """
## Question

Should C1b still require parent gc5 blocks after fcp2?

## Risk assessment

- **Risk Level:** 5 | **Priority:** High | **Importance:** Primary
- **Impact Scope:** system-wide
- **References:** `lessons_coverage_lib.py`, sig:lessons-coverage-c1b-forward-feedback
- **Detail:** fcp3 may relax C1b; user must confirm before epic close.

## Context

- Parent: `.devtool/features/done/agent-parent-2026-06-29.md`
"""


def _write_feedback_card(
    directory: Path,
    name: str,
    *,
    body: str = FEEDBACK_CARD_BODY,
    labels: str = '["feedback"]',
    completed_at: str | None = None,
) -> Path:
    completed_line = f'completedAt: "{completed_at}"\n' if completed_at else ""
    path = directory / name
    path.write_text(
        "---\n"
        f"labels: {labels}\n"
        f"{completed_line}"
        'created: "2026-06-29T20:00:00.000Z"\n'
        "---\n\n"
        f"{body}",
        encoding="utf-8",
    )
    return path


def test_parse_feedback_card_items_extracts_fields():
    items = parse_feedback_card_items(FEEDBACK_CARD_BODY)
    assert len(items) == 1
    item = items[0]
    assert item.question.startswith("Should C1b")
    assert item.risk_level == 5
    assert item.impact_scope == "system-wide"
    assert item.category == "Governance"


def test_derive_feedback_card_category_from_references():
    assert derive_feedback_card_category(references="skill:kanban-markdown") == "Skill"
    assert derive_feedback_card_category(references="rule:testing.mdc") == "Rule"
    assert derive_feedback_card_category(references="helpers/orbit_camera.py") == "Codebase"


def test_build_index_ingests_feedback_card(ff_features):
    repo_root, done = ff_features
    features = repo_root / ".devtool" / "features"
    _write_feedback_card(
        features,
        "feedback-todo.md",
        body=FEEDBACK_CARD_BODY,
    )
    _write_feedback_card(
        done,
        "feedback-done.md",
        body=FEEDBACK_CARD_BODY,
        completed_at="2026-06-29T12:00:00.000Z",
    )
    payload, _warnings = build_index(repo_root=repo_root)
    feedback_rows = [row for row in payload["items"] if "feedback-" in row["source_card"]]
    assert len(feedback_rows) == 2
    assert all(row["risk_level"] == 5 for row in feedback_rows)
    assert feedback_rows[0]["category"] == "Governance"


def test_build_index_preserves_legacy_parent_ff_with_feedback_cards(ff_features):
    repo_root, done = ff_features
    features = repo_root / ".devtool" / "features"
    _write_closed_card(done, "legacy-parent.md", body=_gc5_body())
    _write_feedback_card(features, "feedback-todo.md")
    payload, _warnings = build_index(repo_root=repo_root)
    assert len(payload["items"]) == 7


def test_card_done_spawn_feedback_risk_five_doc_parity():
    """Risk 5 Option A — mandatory feedback spawn documented (fcp2)."""
    paths = (
        REPO_ROOT / ".cursor/skills/kanban-markdown/SKILL.md",
        REPO_ROOT / ".cursor/skills/kanban-markdown/reference.md",
        REPO_ROOT / "docs/governance/forward-feedback.md",
    )
    for path in paths:
        text = path.read_text(encoding="utf-8")
        assert "Risk 5" in text, f"{path} missing Risk 5 spawn policy"
        assert "card-done-feedback-spawn" in text, f"{path} missing signature"
        assert "feedback" in text.lower(), f"{path} missing feedback label reference"
