#!/usr/bin/env python3
"""Build docs/lessons-index.yaml from done/archived kanban lesson captures.

Groups promoted Signatures and governance artifact paths by feature area.
Refresh after Card Done capture or before a quarterly governance audit.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.resolve_prior_lessons import (
    REGISTRY_PATH,
    _closed_card_dirs,
    _lessons_excerpt,
    extract_feature_area_labels,
    extract_governance_artifacts,
    extract_label_paths,
    extract_signatures,
)

INDEX_PATH = REPO_ROOT / "docs" / "lessons-index.yaml"
FEATURE_AREAS_PATH = REPO_ROOT / "docs" / "feature-areas.yaml"
GENERATED_HEADER = (
    "# Generated by scripts/build_lessons_index.py — do not hand-edit sections marked generated.\n"
)
UNCATEGORIZED = "_uncategorized"
_PATH_KEYS = ("paths", "wiring", "tests")
_MAX_REGISTRY_SIGNATURES = 8
_MAX_REGISTRY_DOCS = 5
_LESSON_SIGNATURE_KEY = "lesson_signatures"
_LESSON_DOCS_KEY = "lesson_docs"


def _load_area_registry() -> dict[str, dict[str, Any]]:
    data = yaml.safe_load(REGISTRY_PATH.read_text(encoding="utf-8"))
    areas = data.get("areas", {})
    return areas if isinstance(areas, dict) else {}


def _registry_paths(entry: dict[str, Any]) -> list[str]:
    paths: list[str] = []
    for key in _PATH_KEYS:
        paths.extend(entry.get(key) or [])
    return paths


def _build_path_to_areas(registry: dict[str, dict[str, Any]]) -> dict[str, list[str]]:
    index: dict[str, list[str]] = defaultdict(list)
    for area_name, entry in registry.items():
        for registry_path in _registry_paths(entry):
            index[registry_path].append(area_name)
    return index


def map_card_to_areas(text: str, registry: dict[str, dict[str, Any]]) -> list[str]:
    """Map a card to feature-area keys via labels and uniquely-owned label paths."""
    matched: set[str] = set()
    for label in extract_feature_area_labels(text):
        if label in registry:
            matched.add(label)

    path_index = _build_path_to_areas(registry)
    for label_path in extract_label_paths(text):
        owners = path_index.get(label_path, [])
        if len(owners) == 1:
            matched.add(owners[0])

    if matched:
        return sorted(matched)
    return [UNCATEGORIZED]


def _iter_lesson_cards() -> list[Path]:
    paths: list[Path] = []
    for directory in _closed_card_dirs():
        paths.extend(directory.glob("*.md"))
    return sorted(paths)


def build_index(*, repo_root: Path = REPO_ROOT) -> dict[str, Any]:
    """Return index payload (version, generated_at, areas) from closed cards."""
    registry = _load_area_registry()
    area_data: dict[str, dict[str, set[str]]] = defaultdict(
        lambda: {"signatures": set(), "done_cards": set(), "artifacts": set()}
    )

    features_root = repo_root / ".devtool" / "features"
    if not features_root.is_dir():
        return {
            "version": 1,
            "generated_at": datetime.now(UTC).replace(microsecond=0).isoformat(),
            "areas": {},
        }

    for card_path in _iter_lesson_cards():
        text = card_path.read_text(encoding="utf-8")
        lessons = _lessons_excerpt(text)
        if lessons is None:
            continue

        rel_card = card_path.relative_to(repo_root).as_posix()
        signatures = extract_signatures(lessons)
        artifacts = extract_governance_artifacts(lessons)
        for area in map_card_to_areas(text, registry):
            bucket = area_data[area]
            bucket["done_cards"].add(rel_card)
            bucket["signatures"].update(signatures)
            bucket["artifacts"].update(artifacts)

    areas_out: dict[str, dict[str, list[str]]] = {}
    for area_name in sorted(area_data):
        bucket = area_data[area_name]
        areas_out[area_name] = {
            "signatures": sorted(bucket["signatures"]),
            "done_cards": sorted(bucket["done_cards"]),
            "artifacts": sorted(bucket["artifacts"]),
        }

    return {
        "version": 1,
        "generated_at": datetime.now(UTC).replace(microsecond=0).isoformat(),
        "areas": areas_out,
    }


def render_index_yaml(payload: dict[str, Any]) -> str:
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    return GENERATED_HEADER + body


def write_index(
    payload: dict[str, Any],
    *,
    output_path: Path = INDEX_PATH,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_index_yaml(payload), encoding="utf-8")


def index_is_current(
    payload: dict[str, Any],
    *,
    output_path: Path = INDEX_PATH,
) -> bool:
    if not output_path.is_file():
        return False
    expected = render_index_yaml(payload)
    actual = output_path.read_text(encoding="utf-8")
    return actual == expected


def _load_lessons_index(path: Path = INDEX_PATH) -> dict[str, Any]:
    if not path.is_file():
        return {"areas": {}}
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {"areas": {}}


def _index_doc_paths(artifacts: list[str]) -> list[str]:
    docs = sorted(path for path in artifacts if path.startswith("docs/"))
    return docs[:_MAX_REGISTRY_DOCS]


def propose_registry_lesson_pointers(
    index_payload: dict[str, Any],
) -> dict[str, dict[str, list[str]]]:
    """Map index areas to proposed ``lesson_signatures`` / ``lesson_docs``."""
    proposals: dict[str, dict[str, list[str]]] = {}
    for area_name, bucket in (index_payload.get("areas") or {}).items():
        if area_name == UNCATEGORIZED:
            continue
        raw_sigs = bucket.get("signatures") or []
        signatures = sorted(sig for sig in raw_sigs if sig and sig not in {"…", "..."})[
            :_MAX_REGISTRY_SIGNATURES
        ]
        docs = _index_doc_paths(bucket.get("artifacts") or [])
        if not signatures and not docs:
            continue
        entry: dict[str, list[str]] = {}
        if signatures:
            entry[_LESSON_SIGNATURE_KEY] = signatures
        if docs:
            entry[_LESSON_DOCS_KEY] = docs
        proposals[area_name] = entry
    return proposals


def _current_registry_lesson_pointers(
    registry: dict[str, dict[str, Any]],
    area_name: str,
) -> dict[str, list[str]]:
    entry = registry.get(area_name) or {}
    current: dict[str, list[str]] = {}
    sigs = entry.get(_LESSON_SIGNATURE_KEY) or []
    docs = entry.get(_LESSON_DOCS_KEY) or []
    if sigs:
        current[_LESSON_SIGNATURE_KEY] = list(sigs)
    if docs:
        current[_LESSON_DOCS_KEY] = list(docs)
    return current


def format_registry_sync_diff(
    proposals: dict[str, dict[str, list[str]]],
    *,
    registry: dict[str, dict[str, Any]] | None = None,
) -> str:
    """YAML snippet of proposed lesson pointer changes (dry-run output)."""
    registry = registry if registry is not None else _load_area_registry()
    lines: list[str] = ["# Proposed lesson pointer updates for docs/feature-areas.yaml", ""]
    any_change = False
    for area_name in sorted(proposals):
        proposed = proposals[area_name]
        current = _current_registry_lesson_pointers(registry, area_name)
        if proposed == current:
            continue
        any_change = True
        lines.append(f"{area_name}:")
        for key in (_LESSON_SIGNATURE_KEY, _LESSON_DOCS_KEY):
            values = proposed.get(key)
            if not values:
                continue
            lines.append(f"  {key}:")
            for value in values:
                lines.append(f"    - {value}")
        lines.append("")
    if not any_change:
        return "# Registry lesson pointers already match index proposals\n"
    return "\n".join(lines).rstrip() + "\n"


def sync_registry_lesson_pointers(
    *,
    index_path: Path = INDEX_PATH,
    registry_path: Path = FEATURE_AREAS_PATH,
    write: bool = False,
) -> tuple[dict[str, dict[str, list[str]]], str]:
    """Propose or apply ``lesson_*`` keys from ``docs/lessons-index.yaml``."""
    index_payload = _load_lessons_index(index_path)
    proposals = propose_registry_lesson_pointers(index_payload)
    registry_data = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
    areas = registry_data.get("areas", {})
    if not isinstance(areas, dict):
        areas = {}
    diff_text = format_registry_sync_diff(proposals, registry=areas)

    if write and proposals:
        for area_name, lesson_keys in proposals.items():
            if area_name not in areas:
                continue
            entry = areas[area_name]
            if not isinstance(entry, dict):
                continue
            for key, values in lesson_keys.items():
                entry[key] = values
        registry_data["areas"] = areas
        registry_path.write_text(
            yaml.safe_dump(registry_data, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )

    return proposals, diff_text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 when docs/lessons-index.yaml is stale",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated YAML to stdout instead of writing",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=INDEX_PATH,
        help="Output path (default: docs/lessons-index.yaml)",
    )
    parser.add_argument(
        "--sync-registry",
        action="store_true",
        help="Propose lesson_signatures / lesson_docs updates from the index (dry-run)",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="With --sync-registry, write proposed lesson pointers to feature-areas.yaml",
    )
    args = parser.parse_args(argv)

    if args.sync_registry:
        _, diff_text = sync_registry_lesson_pointers(write=args.write)
        print(diff_text, end="")
        if args.write:
            print(f"Wrote lesson pointers to {FEATURE_AREAS_PATH.relative_to(REPO_ROOT)}")
        return 0

    payload = build_index()
    rendered = render_index_yaml(payload)

    if args.check:
        if not index_is_current(payload, output_path=args.output):
            print(f"{args.output} is stale — run scripts/build_lessons_index.py", file=sys.stderr)
            return 1
        return 0

    if args.dry_run:
        print(rendered, end="")
        return 0

    if not (REPO_ROOT / ".devtool" / "features").is_dir():
        print("Skipping write: .devtool/features not present", file=sys.stderr)
        return 0

    write_index(payload, output_path=args.output)
    print(f"Wrote {args.output.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
