"""Shared forward-feedback index I/O and resolution overlay merge (ff2)."""

from __future__ import annotations

from collections import Counter
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INDEX_PATH = REPO_ROOT / "docs" / "forward-feedback-index.yaml"
INDEX_PATH = DEFAULT_INDEX_PATH
GENERATED_HEADER = "# Generated by scripts/build_forward_feedback_index.py — do not hand-edit.\n"
DEFAULT_STALE_DAYS = 30
DEFAULT_STALE_MIN_RISK = 4
STALE_METRICS_SIGNATURE = "forward-feedback-stale-metrics"
OPEN_FF_STATUSES = frozenset({"open", "discussing"})


def render_index_yaml(payload: dict[str, Any]) -> str:
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True)
    return GENERATED_HEADER + body


VALID_FF_STATUSES = frozenset(
    {
        "open",
        "discussing",
        "answered",
        "spawned",
        "deferred",
        "wont-fix",
        "duplicate",
    }
)

RESOLUTION_OVERLAY_KEYS = (
    "status",
    "spawned",
    "resolution",
    "answered_at",
    "duplicate_of",
)


def load_index(path: Path = DEFAULT_INDEX_PATH) -> dict[str, Any]:
    if not path.is_file():
        return {"version": 1, "items": []}
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {"version": 1, "items": []}


def save_index(payload: dict[str, Any], path: Path = DEFAULT_INDEX_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_index_yaml(payload), encoding="utf-8")


def normalize_card_path(card: str | Path, *, repo_root: Path = REPO_ROOT) -> str:
    """Return repo-relative posix path for a kanban card."""
    raw = Path(card)
    if raw.is_absolute():
        try:
            return raw.resolve().relative_to(repo_root.resolve()).as_posix()
        except ValueError as exc:
            raise ValueError(f"card path outside repo: {card}") from exc
    return raw.as_posix()


def existing_overlays_by_id(path: Path = DEFAULT_INDEX_PATH) -> dict[str, dict[str, Any]]:
    payload = load_index(path)
    records = payload.get("items") or []
    if not isinstance(records, list):
        return {}
    overlays: dict[str, dict[str, Any]] = {}
    for record in records:
        if not isinstance(record, dict):
            continue
        uid = record.get("id")
        if not uid:
            continue
        overlay = {
            key: record[key]
            for key in RESOLUTION_OVERLAY_KEYS
            if key in record and record[key] is not None
        }
        if overlay:
            overlays[str(uid)] = overlay
    return overlays


def merge_resolution_overlays(
    items: list[dict[str, Any]],
    *,
    index_path: Path = DEFAULT_INDEX_PATH,
) -> None:
    """Preserve CLI resolution fields across index rebuilds (ff2)."""
    overlays = existing_overlays_by_id(index_path)
    if not overlays:
        return
    for record in items:
        uid = str(record.get("id") or "")
        overlay = overlays.get(uid)
        if not overlay:
            continue
        rebuild_dup = record.get("duplicate_of")
        for key, value in overlay.items():
            if key == "duplicate_of" and rebuild_dup:
                continue
            record[key] = value
        if rebuild_dup:
            record["duplicate_of"] = rebuild_dup


def apply_duplicate_status(record: dict[str, Any]) -> None:
    """Default duplicate rows to status=duplicate when still open."""
    if record.get("duplicate_of") and str(record.get("status") or "open") == "open":
        record["status"] = "duplicate"


def find_item(
    records: list[dict[str, Any]],
    item_id: str,
) -> dict[str, Any] | None:
    for record in records:
        if record.get("id") == item_id:
            return record
    return None


def is_open_backlog_row(record: dict[str, Any]) -> bool:
    """Active open backlog row — excludes duplicates and terminal statuses."""
    if record.get("duplicate_of"):
        return False
    status = str(record.get("status") or "open")
    if status in {"duplicate", "answered", "spawned", "deferred", "wont-fix"}:
        return False
    return status in OPEN_FF_STATUSES


def risk_band_label(risk_level: int | None) -> str:
    if risk_level is None:
        return "unknown"
    if risk_level >= DEFAULT_STALE_MIN_RISK:
        return "high"
    if risk_level == 3:
        return "medium"
    if risk_level in (1, 2):
        return "low"
    return "unknown"


def parse_completed_date(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(str(value)[:10])
    except ValueError:
        return None


def item_age_days(
    record: dict[str, Any],
    *,
    today: date | None = None,
) -> int | None:
    completed = parse_completed_date(record.get("completed_at"))
    if completed is None:
        return None
    ref = today or datetime.now(UTC).date()
    return (ref - completed).days


def aggregate_open_stats(records: list[dict[str, Any]]) -> dict[str, Any]:
    """Open counts by gc5 category and risk band (ff3)."""
    open_rows = [row for row in records if is_open_backlog_row(row)]
    by_category: Counter[str] = Counter()
    by_risk_band: Counter[str] = Counter()
    by_risk_level: Counter[str] = Counter()
    for row in open_rows:
        by_category[str(row.get("category") or "unknown")] += 1
        risk = row.get("risk_level")
        by_risk_band[risk_band_label(risk if isinstance(risk, int) else None)] += 1
        level_key = str(risk) if isinstance(risk, int) else "unknown"
        by_risk_level[level_key] += 1
    return {
        "total_open": len(open_rows),
        "by_category": dict(sorted(by_category.items())),
        "by_risk_band": {
            band: by_risk_band.get(band, 0) for band in ("high", "medium", "low", "unknown")
        },
        "by_risk_level": dict(sorted(by_risk_level.items())),
    }


def find_stale_high_risk_open(
    records: list[dict[str, Any]],
    *,
    stale_days: int = DEFAULT_STALE_DAYS,
    min_risk: int = DEFAULT_STALE_MIN_RISK,
    today: date | None = None,
) -> list[dict[str, Any]]:
    """High-risk open rows with no spawn older than stale_days since completed_at."""
    stale: list[dict[str, Any]] = []
    for row in records:
        if not is_open_backlog_row(row):
            continue
        risk = row.get("risk_level")
        if not isinstance(risk, int) or risk < min_risk:
            continue
        if row.get("spawned"):
            continue
        age = item_age_days(row, today=today)
        if age is None or age < stale_days:
            continue
        stale.append(row)
    stale.sort(
        key=lambda row: (
            -(row.get("risk_level") or 0),
            -(item_age_days(row, today=today) or 0),
            str(row.get("id") or ""),
        ),
    )
    return stale


def format_open_report_lines(
    stats: dict[str, Any],
    *,
    stale_items: list[dict[str, Any]] | None = None,
    stale_days: int | None = None,
) -> list[str]:
    lines = [
        f"Forward feedback open report (Signature: {STALE_METRICS_SIGNATURE}):",
        f"  total open: {stats['total_open']}",
        "  by category:",
    ]
    if stats["by_category"]:
        for name, count in stats["by_category"].items():
            lines.append(f"    {name}: {count}")
    else:
        lines.append("    (none)")
    lines.append("  by risk band:")
    for band, count in stats["by_risk_band"].items():
        lines.append(f"    {band}: {count}")
    lines.append("  by risk level:")
    if stats["by_risk_level"]:
        for level, count in stats["by_risk_level"].items():
            lines.append(f"    {level}: {count}")
    else:
        lines.append("    (none)")
    if stale_days is not None and stale_items is not None:
        lines.extend(
            format_stale_advisory_lines(
                stale_items,
                stale_days=stale_days,
                prefix="  stale advisory:",
            ),
        )
    return lines


def format_stale_advisory_lines(
    stale_items: list[dict[str, Any]],
    *,
    stale_days: int,
    prefix: str = "",
    today: date | None = None,
) -> list[str]:
    head = f"{prefix} " if prefix else ""
    if not stale_items:
        return [
            f"{head}no high-risk open items exceed {stale_days} day(s) without spawn "
            f"— Signature: {STALE_METRICS_SIGNATURE}",
        ]
    lines = [
        f"{head}{len(stale_items)} high-risk open item(s) with no spawn after "
        f"{stale_days} day(s) (Signature: {STALE_METRICS_SIGNATURE}):",
    ]
    for row in stale_items:
        age = item_age_days(row, today=today)
        age_text = f"{age}d" if age is not None else "unknown-age"
        lines.append(
            f"  [{row.get('id')}] {row.get('category')}: {row.get('question')} "
            f"(risk={row.get('risk_level')}, age={age_text}, "
            f"card={row.get('source_card')})",
        )
    return lines
